name: Create minor release
on:
  push:
    branches:
      - "master"
      - "release/**"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Lint own files
        run: yarn run lint
  create_release:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Determine next version
        run: echo "::set-output name=version::$(./.github/scripts/get-next-version.sh ${{ github.ref_name }})"
        id: next_version
      - name: Next version
        run: echo ${{ steps.next_version.outputs.version }}
      - name: Create release
        if: ${{ steps.next_version.outputs.version != '' }}
        run: |
          gh release create ${{ steps.next_version.outputs.version }} \
            --target ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
